config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  root "book_review#show", page: "home"
  get "book_review/:page", to: "book_review#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, only: [:edit, :update]
  namespace :admin do
    resources :books, expect: [:index, :show]
    resources :users, only: [:update, :destroy]
  end
  resources :genres, only: [:show, :index]
  post "/rate", to: "rater#create", as: "rate"
  resources :users, only: [:show, :index] do
    resources :relationships, only: :index
  end
  resources :books, only: [:show, :index] do
    resources :reviews, except: [:index]
  end
  resources :reviews, only: :index
  resources :relationships, only: [:create, :destroy ]
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews
  has_many :book_genres
  has_many :genres, through: :book_genres

  accepts_nested_attributes_for :genres

  validates :name, presence: true
  validates :introdution, presence: true
  validates :web_ratting, presence: true

  ratyrate_rateable "story"
  mount_uploader :image, ImageUploader

  def overall_ratings
    array = Rate.where rateable_id: id, rateable_type: "book"
    stars = array.map {|this| this.stars}
    star_count = stars.count
    stars_total = stars.inject(0) {|sum,x| sum + x}
    score = stars_total / (star_count.nonzero? || 1)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :check_login
  before_action :check_admin
  before_action :find_book, only: [:edit, :update, :destroy]
  before_action :upload_image, only: [:create, :update]

  def new
    @book = Book.new
    @genres = Genre.all
  end

  def edit
    @genres = Genre.all
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t "success.book"
      redirect_to root_url
    else
      render :new
    end
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t "success.update"
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:success] = t "book.delete"
    redirect_to books_url
  end

  private

  def book_params
    params.require(:book).permit :name, :introdution, :web_ratting,
      :image, :remove_image, :image_cache,
      :remote_image_url,
      genre_ids: [],genres_attributes:[:name]
  end

  def check_admin
    unless current_user.admin?
      flash[:danger] = t "danger.create_book"
      redirect_to root_url
    end
  end

  def check_login
    unless logged_in?
      flash[:danger] = t "danger.login"
      redirect_to login_path
    end
  end

  def find_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:danger] = t "danger.book"
      redirect_to root_url
    end
  end

  def upload_image
    if(params[:book][:image])
        Cloudinary::Uploader.upload(params[:book][:image])
      else
        if(params[:book][:remote_image_url])
        Cloudinary::Uploader.upload(params[:book][:remote_image_url])
        end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
def index
  if params[:search]
    @books = Book.where(name: params[:search]).paginate page: params[:page],
      per_page: 10
  else
    @books = Book.all.paginate page: params[:page],
      per_page: 10
  end
  end

  def show
    @book = Book.find_by id: params[:id]
    if @book
      @reviews = @book.reviews.order(created_at: :desc)
        .paginate page: params[:page], per_page: 10
    else
      flash[:danger] = t "book.not_found"
      redirect_to root_url
    end
  end
end

app/helpers/admin/book_helper.rb
module Admin::BookHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/admin/books/_form.html.erb
<%= form_for @book, url: yield(:url_path), html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", object: @book %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :introdution %>
  <%= f.text_area :introdution, class: "form-control" %>

  <%= f.label :web_ratting %>
  <%= f.number_field :web_ratting, class: "form-control" %>

  <%= f.label :image %><br>
  <%= f.hidden_field :image_cache %>
  <%= f.file_field :image %>
  <% if f.object.image? %>
    <%= image_tag(f.object.image_url,:width => 250, :height => 250) %>
    <p>Remove image:<%= f.check_box :remove_image %></p>
  <% end %>

  <p>Enter URL to an image</p>
  <%= f.text_field :remote_image_url %>

  <% if @genres %>
    <%= f.collection_check_boxes(:genre_ids, @genres, :id, :name)do |id| %>
      <%= id.label class:"label-checkbox" do%>
        <%= id.text %>
        <%= id.check_box %>
      <%end%>
    <% end %>
  <% end %>

  <p><%= f.nested_fields_for :genres do |genre| %>
    <p>Chance genre:
    <%= genre.text_field :name, class: "form-control" %></p>
  <% end %></p>
  <%= f.add_nested_fields_link :genres%>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/books/edit.html.erb
<% provide :title, t("book.update") %>
<% provide :button_text, t("book.update") %>
<% provide :url_path, admin_book_path %>
<h1><%= t "book.update" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/new.html.erb
<% provide :title, t("book.create") %>
<% provide :button_text, t("book.create") %>
<% provide :url_path, admin_books_path %>
<h1><%= t "book.create" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>