config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  root "book_review#show", page: "home"
  get "book_review/:page", to: "book_review#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, only: [:edit, :update]
  namespace :admin do
    resources :books, expect: [:index, :show]
    resources :users, only: [:update, :destroy]
  end
  resources :genres, only: [:show, :index]
  post "/rate", to: "rater#create", as: "rate"
  resources :users, only: [:show, :index] do
    resources :relationships, only: :index
  end
  resources :books, only: [:show, :index] do
    resources :reviews, except: [:index]
  end
  resources :reviews, only: :index
  resources :relationships, only: [:create, :destroy ]
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token, :activation_token, :reset_token

  before_save :downcase_email
  before_create :create_activation_digest

  has_many :reviews
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id
  has_many :followers, through: :passive_relationships, source: :follower

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: {minimum: 6, maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum:6}, allow_blank: true

  has_secure_password

  ratyrate_rater

  mount_uploader :image, ImageUploader

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def activate
    update_attributes activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  def is_user? user
    self == user
  end

  def reviewed? book
    self.reviews.find_by book_id: book.id
  end

  def created? review
    self.reviews.find_by id: review.id
  end

   def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
    user.password = "123456"
    user.activated = true
    user.save!
    user
  end
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user
  before_action :logged_in_user
  before_action :find_user

  def update
    if @user.update_attributes(admin: true)
      flash[:success] = "Success"
      redirect_to users_url
    else
      flash[:danger] = "Set Admin Fail"
      redirect_to users_url
    end
  end

  def destroy
    @user.destroy
    flash[:success] = t "user.delete_success"
    redirect_to users_url
  end

  private

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "danger.not_found"
      redirect_to root_url
    end
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    generic_callback("facebook")
  end

  def google_oauth2
    generic_callback( "google_oauth2" )
  end

  def generic_callback(provider)
    @identity = User.from_omniauth(request.env["omniauth.auth"])

    @user = @identity || current_user
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :find_user, except: [:new, :create, :index]
  before_action :correct_user, only: [:edit, :update]
  before_action :upload_image, only: [:create, :update]

  def index
    if params[:search] == nil
    @users = User.where(activated: true).paginate(page: params[:page])
    else
    @users = User.where(activated: true,name: params[:search]).paginate(page: params[:page])
    end
  end

  def show
    if @user
      @reviews = @user.reviews.order(created_at: :desc)
        .paginate page: params[:page], per_page: Settings.per_page
      @relationship =
        if current_user.active_relationships.find_by followed_id: @user.id
          current_user.active_relationships.find_by followed_id: @user.id
        else
          current_user.active_relationships.build
        end
    else
      flash[:danger] = t "danger.not_found"

    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t "info.activation"
      redirect_to root_url
    else
      render :new
    end
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "success.update"
      redirect_to root_url
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :image, :remove_image, :image_cache,
      :remote_image_url
  end

  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "danger.not_found"
      redirect_to root_url
    end
  end

  def correct_user
    unless current_user.is_user? @user
      flash[:danger] = t "danger.correct_user"
      redirect_to root_url
    end
  end

  def upload_image
    if(params[:user][:image])
        Cloudinary::Uploader.upload(params[:user][:image])
      else
        if(params[:user][:remote_image_url])
        Cloudinary::Uploader.upload(params[:user][:remote_image_url])
        end
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user_helper.rb
module UserHelper
  def gravatar_for(user, options = { size: 80 })
    name = Faker::Name.name
    gravatar_id = Digest::MD5::hexdigest(name)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag("images.jpeg", :width => 250, :height => 250)
  end
end

app/views/users/_follow.html.erb
<%= form_for @relationship, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <div><%= hidden_field_tag :user_id, @user.id %></div>
  <%= f.submit t("follow.title"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.is_user? @user %>
  <div id="follow-form">
    <% if current_user.following?(@user) %>
      <%= render "users/unfollow" %>
    <% else %>
      <%= render "users/follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, url: yield(:url_path), html: {multipart: true} do |f| %>
<%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :image %><br>
  <%= f.hidden_field :image_cache %>
  <%= f.file_field :image %>
  <% if f.object.image? %>
    <%= image_tag(f.object.image_url,:width => 250, :height => 250) %>
    <p>Remove image:<%= f.check_box :remove_image %></p>
  <% end %>

  <p>Enter URL to an image</p>
  <%= f.text_field :remote_image_url %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for @relationship,
  html: {method: :delete}, remote: true do |f| %>
  <div><%= hidden_field_tag :user_id, @user.id %></div>
  <%= f.submit t("follow.unfollow"), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<p><% if user.image.present? %>
   <%= image_tag(user.image_url,:width => 250, :height => 250) %>
   <%else%>
    <%= image_tag("images.jpeg",:width => 250, :height => 250) %>
   <%end%>
<span class="user"><%= link_to user.name, user %>
<% if logged_in? && current_user.admin? && !user.is_user?(current_user) %>
  | <%= link_to t("user.delete"), admin_user_path(user.id) ,method: :delete,
      data: { confirm: t("message.confirm") } %> |
    <%= link_to "Chance to Admin ", admin_user_path(user.id),method: :put,
      data: { confirm: t("message.confirm") } %>
<% end %></span></p>

app/views/users/edit.html.erb
<% provide :title, t("user.edit") %>
<% provide :button_text, t("user.update") %>
<% provide :url_path, user_path %>
<h1><%= t "user.edit.update" %></h1>
<div class ="row">
  <div class ="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t("user_list")) %>
<% provide(:path, users_path )%>

<h1>All users</h1>
<%= render 'shared/search_form' %>
<%= will_paginate %>
<ul class="users">
    <li>
      <%= render @users %>
    </li>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t("header.sign_up")%>
<% provide :button_text, t("user.create") %>
<% provide :url_path, signup_path %>
<h1><%= t "header.sign_up" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<h1>
  <p>
    <p><% if @user.image.present? %>
   <%= image_tag(@user.image_url,:width => 250, :height => 250) %>
   <%else%>
    <%= image_tag("images.jpeg",:width => 250, :height => 250) %>
   <%end%>
    <%= @user.name %>
  </p>
</h1>
<%= render "follow_form" if logged_in? %>
<section class="stats">
  <%= render "shared/stats" %>
</section>
<div class="row">
  <div class="col-md-4">
    <h3><%= t "review.title" %> (<%= @user.reviews.count %>)</h3>
    <% if @user.reviews.any? %>
      <ol class="reviews">
        <%= render @reviews %>
      </ol>
      <p><%= will_paginate @reviews %></p>
    <% end %>
  </div>
</div>