config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  root "book_review#show", page: "home"
  get "book_review/:page", to: "book_review#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, only: [:edit, :update]
  namespace :admin do
    resources :books, expect: [:index, :show]
    resources :users, only: [:update, :destroy]
  end
  resources :genres, only: [:show, :index]
  post "/rate", to: "rater#create", as: "rate"
  resources :users, only: [:show, :index] do
    resources :relationships, only: :index
  end
  resources :books, only: [:show, :index] do
    resources :reviews, except: [:index]
  end
  resources :reviews, only: :index
  resources :relationships, only: [:create, :destroy ]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, except: [:show, :index]
  before_action :find_book, except: [:index]
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :upload_image, only: [:create, :update]

  def index
    if params[:search]
      @reviews = Review.where(title: params[:search]).paginate page: params[:page],
      per_page: Settings.per_page
    else
    @reviews = Review.all.paginate page: params[:page],
      per_page: Settings.per_page
    end
  end

  def show
    @review = Review.find_by id: params[:id]
    unless @review
      flash[:danger] = t "review.not_found"
      redirect_to root_url
    end
  end

  def new
    if current_user.reviewed? @book
      flash[:danger] = t "review.fobid"
      redirect_to root_url
    else
      @review = Review.new
    end
  end

  def create
    @review = current_user.reviews.new review_params
    @review.book_id = @book.id
    if @review.save
      flash[:success] = t "review.created"
      redirect_to book_review_path @book, @review
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update_attributes review_params
      flash[:success] = t "review.updated"
      redirect_to book_review_path @book, @review
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    flash[:success] = t "review.deleted"
    redirect_to root_url
  end

  private

  def review_params
    params.require(:review).permit :title, :content,  :image, :remove_image, :image_cache,
      :remote_image_url
  end

  def find_book
    @book = Book.find params[:book_id]
    unless @book
      flash[:danger] = t "danger.find_book", param: params[:book_id]
      redirect_to root_path
    end
  end

  def find_review
    @review = current_user.reviews.find_by id: params[:id]
    unless @review
      flash[:danger] = t "danger.access"
      redirect_to root_path
    end
  end

  def upload_image
    if(params[:review][:image])
        Cloudinary::Uploader.upload(params[:review][:image])
      else
        if(params[:review][:remote_image_url])
        Cloudinary::Uploader.upload(params[:review][:remote_image_url])
        end
    end
  end
end

app/views/reviews/_form.html.erb
<%= form_for [@book, @review] do |f| %>
  <%= render "shared/error_messages", object: @review %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :image %><br>
  <%= f.hidden_field :image_cache %>
  <%= f.file_field :image %>
  <% if f.object.image? %>
    <%= image_tag(f.object.image_url,:width => 250, :height => 250) %>
    <p>Remove image:<%= f.check_box :remove_image %></p>
  <% end %>

  <%= f.label :content %>
  <%= f.cktext_area :content, rows: 10, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/reviews/_review.html.erb
<li id="review-<%= review.id %>">
    <%= gravatar_for review.user, size: 100 %>
  <span class="title"><%= link_to review.title,
    book_review_path(review.book_id, review) %></span>
  <p><%= link_to review.user.name, review.user %></p>
</li>
<p class="timestamp">
  <%= t "review.created_at", time: time_ago_in_words(review.created_at) %>
</p>

app/views/reviews/edit.html.erb
<% provide :title, t("header.review") %>
<% provide :button_text, t("review.change") %>

<h1><%= t "header.review" %></h1>

<div>
  <%= render "form" %>
</div>

app/views/reviews/index.html.erb
<% provide :title, t("header.review_list") %>
<% provide(:path, reviews_path )%>

<h1><%= t "header.review_list" %></h1>
<%= render 'shared/search_form' %>
<ul class="reviews">
  <% @reviews.each do |review| %>
    <li>
      <p>
        <% if review.image.present? %>
        <%= image_tag(review.image_url,:width => 250, :height => 250) %>
        <%else%>
        <%= image_tag("images.jpeg",:width => 250, :height => 250) %>
        <%end%>
        <%= link_to review.title, book_review_path(review.book_id, review) %>
      </p>
    </li>
  <% end %>
  <p><%= will_paginate @reviews %></p>
</ul>

app/views/reviews/new.html.erb
<% provide :title, "Review" %>
<% provide :button_text, "Create" %>

<h1><%= t "header.review" %></h1>

<div>
  <%= render "form" %>
</div>

app/views/reviews/show.html.erb
<% provide :title, @review.title %>
<h1><%= @review.title %></h1>
<div id="review-<%= @review.id %>">
  <% if @review.image.present? %>
   <%= image_tag(@review.image_url,:width => 250, :height => 250) %>
   <%else%>
    <%= image_tag("images.jpeg",:width => 250, :height => 250) %>
   <%end%>
  <span class="user"><%= link_to @review.user.name, @review.user %></span>
  <p><%= t "review.for" %><%= @book.name %></p>
  <% if logged_in? && current_user.created?(@review) %>
    <%= link_to t("review.destroy"), book_review_path, method: :delete,
      data: {confirm: t("message.confirm")} %>
    <br>
    <%= link_to t("review.edit"), edit_book_review_path(@book) %>
  <% end %>
</div>
<p class="content"><%= @review.content.html_safe %></p>
<p class="timestamp">
  <%= t "review.created_at", time: time_ago_in_words(@review.created_at) %>
</p>