config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  root "book_review#show", page: "home"
  get "book_review/:page", to: "book_review#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, only: [:edit, :update]
  namespace :admin do
    resources :books, expect: [:index, :show]
    resources :users, only: [:update, :destroy]
  end
  resources :genres, only: [:show, :index]
  post "/rate", to: "rater#create", as: "rate"
  resources :users, only: [:show, :index] do
    resources :relationships, only: :index
  end
  resources :books, only: [:show, :index] do
    resources :reviews, except: [:index]
  end
  resources :reviews, only: :index
  resources :relationships, only: [:create, :destroy ]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t("help.title"), "/book_review/help" %></li>
      <li><%= link_to t("about.title"), "/book_review/about" %></li>
      <li><%= link_to t("contact.title"), "/book_review/contact" %></li>
      <li><p>© <%= Date.today.year %> Book Review.</p></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t("name"), root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-center">
      <li><%= link_to t("header.user_list"), users_path %></li>
      <li><%= link_to t("header.book_list"), books_path %></li>
      <li><%= link_to t("header.review_list"), reviews_path %></li>
      <li><%= link_to t("genre.list"), genres_path %></li>
      <% if logged_in?&&current_user.admin? %>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Book Manage <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create book", new_admin_book_path %></li>
          </ul>
        </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t "dropdown.account" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("dropdown.profile"), current_user %></li>
            <li><%= link_to t("dropdown.setting"),
              edit_user_path(id: current_user.id) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to t("dropdown.logout"), logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to t("header.log_in"), login_path %></li>
        <li><%= link_to t("header.sign_up"), signup_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
  <div>
    <%= render "layouts/header" %></div>
    <div class = "container" id= "content">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>